-
  #branches:
    #only:
    #  - * 
    #  - develop
    #  - release
      
  os: Visual Studio 2015
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(GitVersion_AssemblySemVer)'
    assembly_file_version: '$(GitVersion_AssemblySemVer)'
    assembly_informational_version: '$(GitVersion_NuGetVersion)'
    
  install:
    # GitVersion doesn't support SSH, so change the origin remote to an HTTPS URL (if using a private server: 
    # http://help.appveyor.com/discussions/kb/17-getting-gitversion-to-work-with-private-bitbucketgithub-repositories
    # Ensure the GITVERSION_REMOTE_USERNAME and GITVERSION_REMOTE_PASSWORD env variables are set in either this file or the project configuration.  
    - git remote set-url origin https://github.com/daleholborow/iayos.intrinioapi.git
    - GitVersion -output buildserver    
    
  before_build:
   - nuget restore src\iayos.intrinioapi.sln
   - echo %GitVersion_NuGetVersion%
   - cd src\iayos.intrinioapi.Api.Test
   - echo hack to manually create a private settings file so that Test project can copy it during the build and bundle > AppSettings.Private.config
   - cd ..
   - cd ..
     
  build:
    publish_nuget: true  
    verbosity: minimal  
    
  test: off

  configuration:
   - Debug
   
  cache:
   - packages
   
-
  branches:
    only:
      - master
      
  os: Visual Studio 2015
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '$(GitVersion_AssemblySemVer)'
    assembly_file_version: '$(GitVersion_AssemblySemVer)'
    assembly_informational_version: '$(GitVersion_NuGetVersion)'
    
  install:
    # GitVersion doesn't support SSH, so change the origin remote to an HTTPS URL (if using a private server: 
    # http://help.appveyor.com/discussions/kb/17-getting-gitversion-to-work-with-private-bitbucketgithub-repositories
    # Ensure the GITVERSION_REMOTE_USERNAME and GITVERSION_REMOTE_PASSWORD env variables are set in either this file or the project configuration.  
    - git remote set-url origin https://github.com/daleholborow/iayos.intrinioapi.git
    - GitVersion -output buildserver    
    
  before_build:
   - nuget restore src\iayos.intrinioapi.sln
   - echo %GitVersion_NuGetVersion%
  - cd src\iayos.intrinioapi.Api.Test
   - echo hack to manually create a private settings file so that Test project can copy it during the build and bundle > AppSettings.Private.config
   - cd ..
   - cd ..

  build:
    publish_nuget: true  
    verbosity: minimal  
    
  test: off

  configuration:
   - Release
   
  cache:
   - packages
   
  deploy:
    provider: NuGet  
    api_key:
      secure: RecutddoR0t/Ux0kW2FMkNmucowRhtk6W5vWfwAjnodkpf6zLZwr0stBeYiPfBsk
    skip_symbols: true
    artifact: /.*\.nupkg/ 
   